config/routes.rb
Rails.application.routes.draw do



  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user

  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'profiles/show'

  get 'browse', to: 'posts#browse', as: :browse_posts

  localized do
    devise_for :users, :controllers => { registrations: 'registrations' }
    devise_for :admins
    root 'posts#browse'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get ':user_name', to: 'profiles#show', as: :profile



  # New route underneath
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile

  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

end

app/models/post.rb
class Post < ApplicationRecord

  acts_as_votable

  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :image, presence: true
  validates :user_id, presence: true
  validates :caption, length: { minimum: 3, maximum: 300 }

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  scope :of_followed_users, -> (following_users) { where user_id: following_users }


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  require 'open-uri'

  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :authenticate_user!
  before_action :owned_post, only: [:edit, :update, :destroy]
  before_action :loggedin

  def unlike
  if @post.unliked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def like
  if @post.liked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def index
    @posts = Post.of_followed_users(current_user.following).order('created_at DESC').page params[:page]
  end

  def browse
    @posts = Post.all.order('created_at DESC').page params[:page]
  end

  def show
  end

  def new
    @post = current_user.posts.build

    def getHTML(search)
      base1 = "https://pixabay.com/en/photos/?q="
      base2 = "&image_type=&cat=&min_width=&min_height="
      @full_url = base1 + search + base2
      @html = Nokogiri::HTML(open(@full_url)) do |config|
        config.strict.nonet
      end
      @html = @html.to_s
      return @html
    end

    def getUrls(search)
      @final = []
      numberArray = [1,5,7,13,17,19]
      #numberArray = [1,5]
      @htmlpage = getHTML(search)
      numberArray.each do |x|
        @imgcluster = @htmlpage.split(/srcset="(.*?)">/)[x]
        i = @imgcluster.index(", ")
        j = @imgcluster.index(" 2x")
        @final += [@imgcluster[i+2..j-1]]
      end
      return @final
    end

    def uploadImages(search)

      urlstxt = "./app/assets/urls.txt"
      File.open(urlstxt, "a+") { |file| file.puts("Search term: " + search.to_s + " - by user: " + @loggedin.to_s + " at " + Date.today.to_s)}
      baseLocation = './app/assets/images/'
      urls = getUrls(search)
      counter = 1
      finalLocations = []
      urls.each do |url|
        finalLocation = baseLocation + counter.to_s + '.jpg'
        imgLocation = "/assets/" + counter.to_s
        url = url.to_s
        File.open(urlstxt, "a+") { |file| file.puts(url)}

        open(finalLocation.to_s, 'wb') do |file|
          file << open(url).read
        end

        finalLocations += [imgLocation]
        counter += 1
      end
      return finalLocations
    end

    if params[:search].present?
      @counter = [0,1,2,3,4,5]
      @search = params[:search]
      @finalUrls = getUrls(@search)
      @finalImgs = uploadImages(@search)
    end

  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Your post has been created!"
      redirect_to posts_path
    else
      flash[:alert] = "Your new post couldn't be created!  Please check the form."
      render :new
    end
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated hombre"
      redirect_to post_path
    else
      flash.now[:alert] = "Something is wrong with your form!"
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'Problem solved!  Post deleted.'
    redirect_to posts_path
  end

  def edit
  end

  private

  def loggedin
    @loggedin = current_user
  end

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def owned_post
    unless current_user == @post.user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end

end


        #agent = Mechanize.new
        #link = 'https://cdn.pixabay.com/photo/2015/05/22/05/52/cat-778315_1280.jpg'
        #agent.get(link).save finalLocation

app/helpers/posts_helper.rb
module PostsHelper

  def display_likes(post)
    votes = post.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 8
    count_likers(votes)
  end

  def liked_post(post)
    return 'glyphicon-heart' if current_user.voted_for? post
    'glyphicon-heart-empty'
  end

  private

  def list_likers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.user_name,
                                profile_path(voter.user_name),
                                class: 'user-name')
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def count_likers(votes)
    vote_count = votes.size
    vote_count.to_s + ' likes'
  end

  def like_plural(votes)
    # If we more than one like for a post, use ' like this'
    return ' like this' if votes.count > 1
    # Otherwise, return ' likes this'
    ' likes this'
  end
end

app/views/posts/_form.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = form_image_select(@post)
        = simple_form_for @post, html: { multipart: true } do |f|
          .row
            .col-md-12.text-center
              = f.error_notification
          .container-fluid
            .form-group.text-center
              %h4 Upload an image:
              = f.input :image, label: false, input_html: { onChange: 'loadFile(event)' }
            .form-group.text-center
              = f.input :caption, label: false, placeholder: 'Add your caption'
            .form-group.text-center
              = f.button :submit, class: 'btn-success btn-block'

app/views/posts/_likes.html.haml
.likes{id: "likes_#{post.id}"}
  = display_likes post

app/views/posts/_post.html.haml
.posts-wrapper
  .post
    .post-head
      .thumb-img
      .user-name
        = link_to post.user.user_name, profile_path(post.user.user_name)
      .time-ago
        = time_ago_in_words post.created_at
        = "ago"
    .image.center-block
      = link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post)
    .post-bottom
      = render 'posts/likes', post: post
      .caption
        .caption-content
          .user-name
            = link_to post.user.user_name, profile_path(post.user.user_name)
          = post.caption
        .comments{id: "comments_#{post.id}"}
          - if post.comments
            = render post.comments, post: post
    .comment-like-form.row
      .col-sm-1.like-button
        =link_to '', like_post_path(post.id), remote: true,
                                              id: "like_#{post.id}",
                                              class: "glyphicon #{liked_post post}"
      .comment-form.col-sm-11
        = form_for([post, post.comments.build], remote: true) do |f|
          = f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}"

app/views/posts/_post_dashboard.html.haml
#posts
  = render 'posts'
#paginator.text-center
  = link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more'

app/views/posts/_post_dashboard.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }  

app/views/posts/_posts.html.haml
-@posts.each do |post|
  = render 'post', post: post

app/views/posts/browse.html.haml
= render 'post_dashboard', posts: @posts

app/views/posts/edit.html.haml
= render 'form'
.text-center.edit-links
  = link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }
  |
  = link_to "cancel", posts_path

app/views/posts/index.html.haml
= render 'post_dashboard', posts: @posts
.posts-wrapper
  .post
    .post-head
      = link_to "Finnish", root_fi_path

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }  

app/views/posts/like.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#like_<%= @post.id %>").removeAttr('href').attr('href', '/posts/<%= @post.id %>/unlike');
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/posts/new.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = form_image_select(@post)
        = simple_form_for @post, html: { multipart: true } do |f|
          .row
            .col-md-12.text-center
              = f.error_notification
          .container-fluid
            .form-group.text-center
              %h4 Upload an image:
              = f.input :image, label: false, input_html: { onChange: 'loadFile(event)' }

              /= f.input :username, :image_tag '/assets/1.jpg'

              /%h4 Need this as f.input
              /= image_tag '/assets/1.jpg', width: '200'

            .form-group.text-center
              = f.input :caption, label: false, placeholder: 'Add your caption'
            .form-group.text-center
              = f.button :submit, class: 'btn-success btn-block'

        .container-fluid
          .form-group.text-center
            = form_tag(new_post_path, :method => "get", id: "seach-form", :multipart => true) do
              = text_field_tag :search, params[:search], placeholder: "E.g. dog"
              / search area
          .form-group.text-center
            = submit_tag "Search Images", class: "btn-success btn-block"
      .form-group.text-center
        /finalImgs = local path
        /finalUrl = Image URL
        - if (@finalImgs != nil) then
          - if (@finalUrls != nil) then
            - @counter.each do |x|
              = link_to image_tag(@finalImgs[x], width: '200'), @finalUrls[x]

app/views/posts/show.html.haml
= render 'post', post: @post
.text-center.edit-links
  - if @post.user.id == current_user.id
    = link_to 'Cancel', posts_path
    |
    = link_to 'Edit Post', edit_post_path(@post)
  - else
    = link_to 'Cancel', posts_path

app/views/posts/unlike.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart').addClass('glyphicon-heart-empty');
$("#like_<%= @post.id %>").removeAttr('href').attr('href', '/posts/<%= @post.id %>/like');
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");