config/routes.rb
Rails.application.routes.draw do



  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user

  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get 'profiles/show'

  get 'browse', to: 'posts#browse', as: :browse_posts

  localized do
    devise_for :users, :controllers => { registrations: 'registrations' }
    devise_for :admins
    root 'posts#browse'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get ':user_name', to: 'profiles#show', as: :profile



  # New route underneath
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile

  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid.navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
      .navbar-brand= link_to "HipsterGram", root_path
    .collapse.navbar-collapse#bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to t('admin'), rails_admin_path
          %li
            = link_to t('feed'), root_path
          %li
            = link_to t('profile'), profile_path(current_user.user_name)
          %li
            = link_to t('discover'), browse_posts_path
          %li
            = link_to t('newpost'), new_post_path
          %li
            = link_to t('logout'), destroy_user_session_path, method: :delete
        - else
          %li
            = link_to t('login'), new_user_session_path
          %li
            = link_to t('register'), new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HipsterGram
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    .container
      -flash.each do |name, msg, notice, alert|
        = content_tag :div, msg, class: [:alert, alert_for(name)]

    = yield